# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors_count', models.IntegerField()),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('created_at', models.TimeField(auto_now=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Goods')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='orders',
            name='preorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Preorder'),
        ),
        migrations.AddField(
            model_name='orderplaces',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Orders'),
        ),
        migrations.AddField(
            model_name='orderplaces',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Places'),
        ),
    ]
