# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20161218_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='first_good',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preorder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='visitors_count',
        ),
        migrations.AddField(
            model_name='goods',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='booking_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Preorder',
        ),
    ]
