# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161224_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Goods'),
        ),
    ]
