# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161225_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('decert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Goods')),
                ('drink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Goods')),
                ('main_food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Goods')),
                ('salad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Goods')),
                ('soup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Goods')),
            ],
        ),
    ]
