# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_spisok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='good',
        ),
        migrations.AddField(
            model_name='order',
            name='spisok',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Spisok'),
        ),
        migrations.AlterField(
            model_name='spisok',
            name='decert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Decert'),
        ),
        migrations.AlterField(
            model_name='spisok',
            name='drink',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Drink'),
        ),
        migrations.AlterField(
            model_name='spisok',
            name='main_food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.MainFood'),
        ),
        migrations.AlterField(
            model_name='spisok',
            name='salad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Salad'),
        ),
        migrations.AlterField(
            model_name='spisok',
            name='soup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Soup'),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
