# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170217_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spisok',
            name='decert',
        ),
        migrations.RemoveField(
            model_name='spisok',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='spisok',
            name='main_food',
        ),
        migrations.RemoveField(
            model_name='spisok',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='spisok',
            name='soup',
        ),
        migrations.RemoveField(
            model_name='order',
            name='spisok',
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='decert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Decert'),
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='main_food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.MainFood'),
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='soup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Soup'),
        ),
        migrations.DeleteModel(
            name='Spisok',
        ),
    ]
